baseurl = "https://beautician-jocelyn-35104.netlify.com/"
languageCode = "en-US"
title = "Jake Russ"
# Enable comments by entering your Disqus shortname
disqusShortname = "jake_russ"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-44185619-1"
theme = "hugo-sustain"

[permalinks]
  blog = "/blog/:slug/"
  cheatsheets = "cheatsheets/:slug/"

[params]
  avatar = "jake.jpg"
  author = "Jake Russ"
  description = "economist and statistical programmer"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "jakeruss"
  Email         = "jake.w.russ@gmail.com"
  Twitter       = "jakeruss"
  LinkedIn      = "jakeruss"
  Stackoverflow = "users/2878990/jake-russ"

## Main Menu
[[menu.main]]
  name       = "about"
  identifier = "about"
  weight     = 100
  url        = "/about/"
[[menu.main]]
  name       = "blog"
  identifier = "blog"
  weight     = 200
  url        = "/blog/"
[[menu.main]]
  name       = "cheatsheets"
  identifier = "cheatsheets"
  weight     = 300
  url        = "/cheatsheets/"
[[menu.main]]
  name       = "papers"
  identifier = "papers"
  weight     = 400
  url        = "/papers/"
[[menu.main]]
  name       = "resume"
  identifier = "resume"
  weight     = 500
  url        = "/resume/"
[[menu.main]]
  name       = "restaurant-guide"
  identifier = "restaurant-guide"
  weight     = 600
  url        = "/restaurant-guide/"
